# Generated by Django 4.2 on 2023-04-12 04:58

import api.models.productModels
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_comment_comment_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='images/core/no_image.png', upload_to=api.models.productModels.user_images_path),
        ),
    ]
