# Generated by Django 4.2 on 2023-04-12 05:04

import api.models.productModels
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_notification_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='images/no_image.png', upload_to=api.models.productModels.user_images_path),
        ),
    ]
