# Generated by Django 4.2 on 2023-04-12 05:27

import api.models.productModels
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentor_id',
            new_name='commentor',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='images/core/no_image.png', upload_to=api.models.productModels.user_images_path),
        ),
    ]
