# Generated by Django 4.2 on 2023-04-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_commentor_id_comment_commentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='actual_cost',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
